### ISSUE TITLE
[BUG] Explore Shibboleth login failure due to deleted UUID

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/safer-illinois-app#508]
**Describe the bug**
This was an earlier bug that had been fixed. It looks like it has reappeared recently. For many users, the first UUID in the UUID list in their Profile PII record seems to have got deleted from the Non-PII collection. So, when they try to login and we switch to their first UUID (which is non-existent) now, it will appear to the user that the login failed.

**To Reproduce**
So far no specific steps to reproduce this issue has been identified. From users, we have collated some scenarios during which they are running into this issue. These may be helpful as clues:

1. Many users hadn't used the app for an extended period. When they open the app, they will be logged out. When they login again they get "Unable to login" message.
2. Other users ran into this when tried to switch to a new or a second device.

**Expected behavior**
The first UUID in the PII UUID list should not get deleted from the Non-PII database.

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: iOS and Android
 - Version 2.9.4

**Additional context**

**Comment by mdryankov** [comment]
@sandeep-ps, the only place where delete user profile is invoked is where "Delete Personal Info" is executed as functionality.

Also from client perspective this inapropriate deletion is possible if the user is logged in but the token and refresh token have been expired and he/she tries to delete his data. In this case the delete Pii request will failed, but the next one is to delete the profile data...

Also could you please put more info about POST https://<oidc>@shibboleth.illinois.edu/idp/profile/oidc/token request all possible status codes and response variations?
We need it in order to make appropriate handling of the refresh token client side

**Comment by sandeep-ps** [comment]
>Also from client perspective this inapropriate deletion is possible if the user is logged in but the token and refresh token have been expired and the user tries to delete his data. In this case the delete Pii request will failed, but the next one is to delete the profile data...

Thanks for catching this. Yes, deleting PII and Non-PII data needs to be done together from the client.

**Comment by mdryankov** [comment]
Thanks @sandeep-ps , 

We covered it in Safer 2.9.8 & UIUC 2.4. However we need an info from Shibboleth Manager  for refresh token status codes and responses in order to logout only on the desired status code. The current state only cleans partially the state and - which is not good and must be fix appropriately.

**Comment by sandeep-ps** [comment]
Okay. Thanks. What are the current responses that you are getting? 

I was looking at the OIDC documentation/spec. For different error situations, it looks like the most common error response is HTTP 400 Bad Request. Refs: https://openid.net/specs/openid-connect-core-1_0.html#RefreshErrorResponse, https://tools.ietf.org/html/rfc6749#section-5.2.

Anyway, I'll get a confirmation on this.

**Comment by mdryankov** [comment]
Let's rephrase my question. In what situation (e.g response code) the client must interpred it and forse logout?

Today we had long discussion with Misho and we think not every refresh falilure must be interpred as logout, because for example temporary network issue may forse the client to logout unexpectedly - we're trying to cover such situation where logout is not need and may try another refresh at later stage

CC @pmarkhennessy

**Comment by sandeep-ps** [comment]
Okay. Got it. I have asked the Shibboleth Manager's opinion on this. I will share the details here as and as soon as I get a response. Thanks.

**Comment by mdryankov** [comment]
Assign to @sandeep-ps  for validation. 

Refresh token would logout the user if the endpoint result error 401 or 403 - In addition to the above fixes.
This is applied for UIUC latest ver. & Safer Illinois 2.9 & 2.10

**Comment by sandeep-ps** [comment]
@mdryankov, I got confirmation from Shibboleth Manager that the response status code for expired refresh token will be `HTTP 400 Bad Request` and the response JSON body will contain property `error` with value `invalid_grant`. I think these can be used to log a user out during the refresh token update step.

**Comment by sandeep-ps** [comment]
Thanks. Closing this as we are seeing fewer issues these days.
