### ISSUE TITLE
[BUG]  Safer Illinois Home screen is not updated

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#600]
**Describe the bug**
Safer Illinois Home screen is not updated, when the user didn't verify his identity while onboarding and verified via "Connect your NetID" on the Safer Illinois Home screen.

**To Reproduce**
1. Install Safer app
2. University Student role is selected in "Who are you?" screen
3. Tap on **"Not Right now"** on Connect your NetID screen
4. Complete the Covid onboarding screen
5. Safer home screen is displayed.
6. Tap on Connect your NetID button
7. Enter the login credentials in the Shib screen and verify the student identity

**Actual Result**
As the user connected the app using the NetID, the Safer Illinois Home screen has to be updated. But it was showing the same information "Connect to Illinois"

Note - The setting screen has updated user information once the user verified his identity.

**Expected behavior**
As the user connected the app using the NetID, the Safer Illinois Home screen has to be updated

**Screenshots**
**Home screen after the user connected the app via Net ID**

![connect to illinois](https://user-images.githubusercontent.com/26231179/115467736-985a9780-a1f7-11eb-9684-d907c0354507.png)

**The setting screen has updated after the user connected the app via Net ID**

![setting connect](https://user-images.githubusercontent.com/26231179/115467767-a3152c80-a1f7-11eb-865f-57b04220bc16.png)

Additional NOTE
The same issue apply to Verify your Phone number 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version - 2.10.18-prod.apk

**Additional context**

**Comment by mdryankov** [comment]
@Priyaravi8 @pmarkhennessy 

I'm unable t reproduce it. Everything & everywhere related is reloaded accordingly. I have noticed only a slight delay due to several post login requests - but nothing more. 

If that delay is the main concern - I would propose to show a modal loading bar during this process? What do you think?

**Comment by Priyaravi8** [comment]
@mdryankov - Today I am not able to reproduce this issue. But I see the following issue

1. Once a user connects the app using his Netid.
2. The home screen is updated Current status duplicated the info "Not Available". Please see the screenshot

![not Avilable](https://user-images.githubusercontent.com/26231179/115750636-fe612f00-a35d-11eb-9ace-1be4ba9be547.png)
.

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate the both problems that you talk about in this GIT issue.

Regarding the second one (Status NA): This could happen if the RSA private key (the COVID-19 QR code) is not properly setup. Was this the case? I am also wondering what the Status panel shows in this case?

**Comment by Priyaravi8** [comment]
@mihail-varbanov  -  For the 2nd issue - 
1. While covid onboarding RSA private key (the COVID-19 QR code) screen is not displayed.
2. **Added the screen shot of Status panel.**
![Stus panel 1](https://user-images.githubusercontent.com/26231179/115893291-9ffb8580-a41d-11eb-8035-f5ba72ca3498.png)
![SP2](https://user-images.githubusercontent.com/26231179/115893300-a2f67600-a41d-11eb-8587-c1978f86e771.png)
![SP3](https://user-images.githubusercontent.com/26231179/115893313-a558d000-a41d-11eb-8152-a92af95bbc20.png)

**Added the Screen shot of setting screen**

![Sp4](https://user-images.githubusercontent.com/26231179/115893424-c5888f00-a41d-11eb-8d77-89e8ed0ef220.png)

**Comment by mihail-varbanov** [comment]
@Priyaravi8 , it is clear way: "Missing COVID-19 private key", as I initially supposed. You have to import an existing private key for this user from other device, or reset it. Then the second issue should disappear.

**Comment by Priyaravi8** [comment]
@mihail-varbanov - From the users stand point, it would be better if we add a message like "import an existing private key from another device, or reset it" on the Safer Home screen instead of the current status displays the information "Not available" and too duplicated.

**Comment by mihail-varbanov** [comment]
@Priyaravi8, the proper handling of missing/mispaired RSA keys requires much more than changing the message in Status widget from the Home panel. The situation is very similar to a user not being logged in because he/she cannot access his/her health history or status. So what I am trying to say is that the proper handling requires removing the health status widget or the access to Health history, as well as adding some new widget that is similar to COVID-19 keys section from Settings panel that allows loading/scanning/resetting COVID-19 key. In general we need to perform some behavior that is very similar to the one when the user is not logged in. This is a major change that requires app design update and time for development as this is not quick and simple.

My suggestion is to close this issue because it was opened for something totally different, and let the management decide whether they want the above update now.

CC @pmarkhennessy, @johnmpaul, @joegrohens

**Comment by Priyaravi8** [comment]
Closing this issue and open a new issue for -"missing/mispaired RSA keys" under the usability tag.
