### ISSUE TITLE
[FEATURE] Health rules update

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/safer-illinois-app#668]
**Re: University Monday 2021/07/05** / 2021-07-07

1 Misho - Safer Illinois rule change. We have battled with the University but this is what they want:

1.1 If you have gotten vaccinated (vaccine effective) you get green status

1.2 The only event that can come after the vaccine event and change your status is a positive test

1.3 After either 10 days have passed from the positive test or a “quarantine off” message is received the person should regain their green status

1.4 If another positive event happens before the 10 days or "quarantine off" then we start counting the 10 days again or we get a “quarantine off”

**Comment by isaac-galvan** [comment]
Hello @mihail-varbanov, I see the new rules in place, but the behavior of the app still seems off.
Steps to recreate:

1. Add a "vaccine effective" event, turn green/allowed.
2. Add a positive test, turn red/denied.
3. Add a "quarantine-off" event, turn yellow/denied.

In step 4, the user should turn back to green/allowed because they have an effective vaccine in the history.

I am using 2.10.29 in the test environment.

**Comment by mihail-varbanov** [comment]
@isaac-galvan , you should use 2.10.31 in any environment.
