### ISSUE TITLE
[BUG] Vaccinated users  showing Test required

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#726]
**Describe the bug**
The users who are vaccinated showing "Orange Test required" status in the app

**To Reproduce**

**Note - Vaccinated user**

1. Install the app on 2nd device
2. Role is Student user already vaccinated
3. Complete the onboarding and proceed to the home screen

**Actual Result**
User status is displayed with Orange - Test required for the vaccinated user.  
Note - Vaccine widget is missing for this user.

**Expected behavior**
User status should be Green. 
**Note - App didn't provide QR transfer/Scan/Reset option to the user**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 2.11.3]

**Comment by Priyaravi8** [comment]
Status is updated to Green after few mins.  But App didn't provide QR transfer/Scan/Reset option to the user

**Comment by mihail-varbanov** [comment]
I was not able to recreate this issue.

The app always provides a QR code option: either save in case it it available, or Scan/Load/Reset in case it is not. Could you please send a screenshot of "app didn't provide QR transfer/Scan/Reset option to the user". Anyway, if there was a problem with linking the NetId to the corresponding health account, the described behavior is quite possible due to encryption keys mismatch.

BTW, yesterday all rokwire.illinois.edu services were very unstable, working occasionally and often being down. This might be the reason for app misbehavior.

Please check it again or provide a recreation scenario.

**Comment by Priyaravi8** [comment]
Not able to reproduce this issue in new version
